name: "snyk code manual test"
on: [workflow_dispatch, pull_request]

jobs:
  build:
    name: sarif testing action
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v2
      - name: Setup Snyk
        uses: snyk/actions/setup@master
      - name: Run Snyk to check for vulnerabilities
        run: snyk code test --sarif-file-output=results.sarif
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
